### ISSUE TITLE
Event manager does not exist when using named session/document manager.

### ISSUE THREAD

**Issue by v1nc3n4** [doctrine/phpcr-odm#383]
Hi,

I'm just trying to configure Doctrine PHPCR-ODM with multiple sessions, as shown in the Symfony CMF docs, but when I execute any Symfony command, such as 'php app\console cache:clear', I get the error below:

The service definition "doctrine_phpcr.odm.default_session.event_manager" does not exist.

First of all, I couldn't find any reference documentation in GitHub and the Doctrine Project website about the ODM configuration, it's really a pity.
Only Symfony CMF http://symfony.com/doc/current/cmf/bundles/phpcr_odm.html#configuring-multiple-sessions mentions (all?) the configuration options available, but I'm not even sure this is an updated revision.
Trying to figure out what's causing this error, I finally reduced my PHPCR configuration to the following, and still getting the same error:

```
doctrine_phpcr:
    session:
        default_session: mysession
        sessions:
            mysession:
                backend:
                    type: doctrinedbal
                    connection: myconnection
                    check_login_on_server: true
                workspace: default
                username: admin
                password: admin
    odm:
        default_document_manager: mydocumentmanager
        auto_generate_proxy_classes: %kernel.debug%
        document_managers:
            mydocumentmanager:
                session: mysession
                auto_mapping: true
```

Finally, if I replace 'mysession' and 'mydocumentmanager' references with 'default', the error disappears, but any other combination still leads to this error. It seems there is a remaining 'default' configuration hard-coded in the bundle.

Or maybe a 'default' named-session and a 'default' named-document manager are mandatory. Once again, it is not clear in the documentation, and if so I can't understand why there would be a 'default_session' key and a 'default_document_manager' key.

Thanks in advance for your clarifications, feel free to tell me what I've done wrong!
BR
Vicente
