### ISSUE TITLE
ID strategy overriden to 'assigned' in 'children' properties

### ISSUE THREAD

**Issue by v1nc3n4** [doctrine/phpcr-odm#388]
Hi,
I'm working with a set of 3 documents - let's say `Container`, `AbstractChild`, `ChildImpl` classes.
The `Container` class has a `mychildren` property being a collection of `AbstractChild` implementations (i.e. `ChildImpl` instances).
I want the container and abstract child documents to use an 'auto' generated ID.
I expect the container to have a path like '/[...]/containerId', and child documents '/[...]/containerId/childId'.
These documents have this YAML mapping:

```
Container:
  id:
    fieldName: 'path'
    generator:
      strategy: 'auto'
  parentdocument: 'parentDocument'
  children:
    mychildren:
      cascade: ['persist']
```

```
AbstractChild:
  mappedsuperclass: true
  id:
    fieldName: 'path'
    generator:
      strategy: 'auto'
```

```
ChildImpl:
  fields:
    myproperty:
      type: 'string'

```

`id` generation is OK for the `Container`document.
When persisting the `Container` document, with the 'cascade' property, `mychildren` are also persisted.
But I got an error: the UnitOfWork (line 752) complain the `nodename` property may not be empty in document of class `AbstractChild`.

I found this really strange because I set the ID strategy to 'auto' in the `AbstractChild` document. Finally, after code analysis, it seems this is due to the code located at Doctrine\ODM\PHPCR\UnitOfWork.php (748:755).
It seems that children properties can use only 'assigned' ID strategy. Whatever strategy is configured, the 'assigned' one will override it.

Can you confirm the ODM doesn't support 'auto' ID strategy with children properties?
Thus this would not be a real issue, more an 'incomplete' docs issue ;).
Documentation is a bit obscur about how to configure children documents, especially with the 'Id', 'NodeName' and 'ParentDocument' settings (see http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/annotations-reference.html#children).
If I use the 'assigned' ID strategy, setting the nodename manually, persisting the container document and the children works well :).
Thanks for your clarifications, and any remarks about what I'm trying to do!
BR.
