### ISSUE TITLE
ReferenceManyCollection count() is incorrect

### ISSUE THREAD

**Issue by oste** [doctrine/phpcr-odm#489]
I have two documents a Category and a Block they are mapped like this.

```
AppBundle\Document\Category:
    type: Document
    referenceable: true
    referrers:
        blocks:
            referringDocument: AppBundle\Document\Block
            referencedBy: categories
```

and 

```
AppBundle\Document\Block:
    type: Document
    referenceable: true
    referenceMany:
        categories:
            strategy: weak
```

so in my Block class I have a constructor and getter for the categories that look like this

```
    public function __construct($name = null)
    {
        parent::__construct($name);
        $this->categories = new ArrayCollection();
    }
    public function getCategories()
    {
        return $this->categories;
    }
```

And here is my test that fails

```
       //add a category to a block
        $category = new Category('name');
        $this->dm->persist($category);

        $this->block = new Block('block');
        $this->block->getCategories()->add($category);
        $this->dm->persist($block);
        $this->dm->flush();

       //remove the category and make sure it is not still with the block
       $this->dm->remove($block->getCategories()->first());
       $this->dm->flush();
       $this->dm->refresh($block);
      var_dump($block->getCategories()->count());//THIS IS 1
```

The reason this is happening is because when I call getCategories in the last line it returns ReferenceManyCollection instead of ArrayCollection. The ReferenceManyCollection adds a check for initialization here https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/ReferenceManyCollection.php#L81-L83

If I remove this highlighted code things work as expected that is the last line will print 0 instead of 1...

To fix this we should either add a new method to to ReferenceManyCollection for `getreferencedNodes` and leave the `count` untouched or make sure that getCategories will always return an `ArrayCollection`. I prefer the first option as the check seems to be a hack however i am unsure all of the places it is used so i may not be the bet for a PR.

Thanks, looking forward to resolving this :)
