### ISSUE TITLE
Having problem with 2 ODM managers 

### ISSUE THREAD

**Issue by rivaros** [doctrine/phpcr-odm#752]
Have no other way but to ask. I am trying to use 2 PHPCR ODM document managers for my project.

```
# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    ......
    # enable the ODM layer
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        document_managers:
            default:
                session: default
                mappings:
                    MMPGlobalServicesBundle: ~
            secondary:
                session: secondary
                mappings:
                    MMPGlobalServicesBundle: ~
        .....
```
The problem is that though they have SAME configuration, the complete mapping:info is available only for first one (default). See below:
```
php app/console doctrine:phpcr:mapping:info
Found 43 documents mapped in document manager:
[OK]   MMP\GlobalServicesBundle\Document\DemoClassContent
[OK]   MMP\GlobalServicesBundle\Document\DemoTemplateContent
[OK]   MMP\GlobalServicesBundle\Document\EmailContent
[OK]   MMP\GlobalServicesBundle\Document\Image
[OK]   MMP\GlobalServicesBundle\Document\SecuredMenuNode
[OK]   MMP\GlobalServicesBundle\Document\SliderImage
[OK]   Doctrine\ODM\PHPCR\Document\AbstractFile
[OK]   Doctrine\ODM\PHPCR\Document\File
[OK]   Doctrine\ODM\PHPCR\Document\Folder
[OK]   Doctrine\ODM\PHPCR\Document\Generic
[OK]   Doctrine\ODM\PHPCR\Document\Resource
[OK]   Symfony\Component\Routing\Route
[OK]   Symfony\Cmf\Bundle\RoutingBundle\Model\RedirectRoute
[OK]   Symfony\Cmf\Bundle\RoutingBundle\Model\Route
[OK]   Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
[OK]   Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
[OK]   Symfony\Cmf\Bundle\MenuBundle\Model\Menu
[OK]   Symfony\Cmf\Bundle\MenuBundle\Model\MenuNode
[OK]   Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeBase
[OK]   Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu
[OK]   Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
[OK]   Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNodeBase
[OK]   Symfony\Cmf\Bundle\ContentBundle\Model\StaticContent
[OK]   Symfony\Cmf\Bundle\ContentBundle\Model\StaticContentBase
[OK]   Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent
[OK]   Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContentBase
[OK]   Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page
[OK]   Symfony\Cmf\Bundle\BlockBundle\Model\AbstractBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\AbstractBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\MenuBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
[OK]   Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock
[OK]   Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\AbstractMedia
[OK]   Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Directory
[OK]   Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\File
[OK]   Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image
[OK]   Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Media
```
The second one (secondary) has a problem
```
php app/console doctrine:phpcr:mapping:info --session=secondary
Found 11 documents mapped in document manager:
[OK]   MMP\GlobalServicesBundle\Document\DemoClassContent
[OK]   MMP\GlobalServicesBundle\Document\DemoTemplateContent
[OK]   MMP\GlobalServicesBundle\Document\EmailContent
[OK]   MMP\GlobalServicesBundle\Document\Image
[OK]   MMP\GlobalServicesBundle\Document\SliderImage
[OK]   Doctrine\ODM\PHPCR\Document\AbstractFile
[OK]   Doctrine\ODM\PHPCR\Document\File
[OK]   Doctrine\ODM\PHPCR\Document\Folder
[OK]   Doctrine\ODM\PHPCR\Document\Generic
[OK]   Doctrine\ODM\PHPCR\Document\Resource
```

As you may see all chain of phpcr namespaces (related to PhpcrMappingPass) are not loaded. So I am unable to use the secondary document manager and get consequent errors like

```
The class 'Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page' was not found in the chain configured namespaces MMP\GlobalServicesBundle\Document, Doctrine\ODM\PHPCR\Document
```
